artifact_location: /albedo/work/projects/p_OZA_AI/YOLO/Code/runs/mlflow/417349920177002931
creation_time: 1769597940197
experiment_id: '417349920177002931'
last_update_time: 1769597940197
lifecycle_stage: active
name: /albedo/work/projects/p_OZA_AI/YOLO/runs/biodcase_baseline
